from __future__ import annotations

from typing import Dict, List

import numpy as np
import pandas as pd

from src.config.dataclasses import HealthcareInstance
from src.markov.transition_utils import (
    get_state_index_map,
    load_transition_matrices,
)


def _get_sorted_days(instance: HealthcareInstance) -> List[int]:
    """Return sorted planning days from arrivals data."""
    days = sorted(instance.arrivals.df["day"].unique().tolist())
    return [int(day) for day in days]


def _get_hospitals(instance: HealthcareInstance) -> List[str]:
    """Return sorted hospital IDs."""
    hospitals = sorted(instance.hospitals.df["hospital_id"].unique().tolist())
    return [str(h) for h in hospitals]


def _build_single_patient_c3_paths(
    transition_matrix: np.ndarray,
    days: List[int],
) -> Dict[int, np.ndarray]:
    """
    Build expected state vectors over time for one c3 patient admitted into ED.

    Interpretation:
    - On admit_day = tau, one patient is injected into ED.
    - After one Markov step, we obtain the state vector for day tau.
    - Subsequent days continue propagating through the same transition matrix.

    Returns
    -------
    Dict[int, np.ndarray]
        Mapping relative_day_index -> expected state vector
        where relative_day_index = 0 corresponds to the admit day itself.
    """
    state_to_idx = get_state_index_map()
    n_states = len(state_to_idx)

    ed_init = np.zeros(n_states, dtype=float)
    ed_init[state_to_idx["ED"]] = 1.0

    vectors: Dict[int, np.ndarray] = {}

    current = ed_init @ transition_matrix
    vectors[0] = current.copy()

    for rel_idx in range(1, len(days)):
        current = current @ transition_matrix
        vectors[rel_idx] = current.copy()

    return vectors


def build_c3_elective_response_table(
    instance: HealthcareInstance,
) -> pd.DataFrame:
    """
    Build the marginal expected resource-demand response of one c3 elective admission.

    Output columns:
        hospital_id
        admit_day
        day
        resource
        marginal_demand

    Interpretation:
    - marginal_demand is the expected ICU/Ward demand on 'day'
      caused by one additional c3 elective patient admitted at 'admit_day'
      at the same hospital.
    """
    days = _get_sorted_days(instance)
    hospitals = _get_hospitals(instance)

    transition_matrices = load_transition_matrices(instance.transitions)
    c3_matrix = transition_matrices["c3"]

    state_to_idx = get_state_index_map()
    icu_idx = state_to_idx["ICU"]
    ward_idx = state_to_idx["Ward"]

    relative_paths = _build_single_patient_c3_paths(
        transition_matrix=c3_matrix,
        days=days,
    )

    records = []

    for hospital_id in hospitals:
        for admit_pos, admit_day in enumerate(days):
            max_rel = len(days) - admit_pos - 1

            for rel_idx in range(max_rel + 1):
                demand_day = days[admit_pos + rel_idx]
                state_vec = relative_paths[rel_idx]

                records.append(
                    {
                        "hospital_id": hospital_id,
                        "admit_day": int(admit_day),
                        "day": int(demand_day),
                        "resource": "ICU",
                        "marginal_demand": float(state_vec[icu_idx]),
                    }
                )
                records.append(
                    {
                        "hospital_id": hospital_id,
                        "admit_day": int(admit_day),
                        "day": int(demand_day),
                        "resource": "Ward",
                        "marginal_demand": float(state_vec[ward_idx]),
                    }
                )

    response_df = pd.DataFrame(records)
    response_df = response_df.sort_values(
        ["hospital_id", "admit_day", "day", "resource"]
    ).reset_index(drop=True)

    return response_df


def summarize_same_day_response(
    response_df: pd.DataFrame,
) -> pd.DataFrame:
    """
    Return same-day marginal response only, i.e. admit_day == day.
    """
    same_day = response_df[response_df["admit_day"] == response_df["day"]].copy()
    same_day = same_day.sort_values(
        ["hospital_id", "day", "resource"]
    ).reset_index(drop=True)
    return same_day


def summarize_total_response_by_admit_day(
    response_df: pd.DataFrame,
) -> pd.DataFrame:
    """
    Aggregate the full-horizon marginal ICU/Ward demand generated by one admission.

    Returns
    -------
    pd.DataFrame
        Columns:
            hospital_id
            admit_day
            resource
            total_marginal_demand
    """
    summary = (
        response_df.groupby(
            ["hospital_id", "admit_day", "resource"], as_index=False
        )["marginal_demand"]
        .sum()
        .rename(columns={"marginal_demand": "total_marginal_demand"})
        .sort_values(["hospital_id", "admit_day", "resource"])
        .reset_index(drop=True)
    )
    return summary